import type { DrawingItem } from '@/types';

import { buildItems, toSteps } from '../_helpers';

export const animals: DrawingItem[] = buildItems('animals', [
  {
    slug: 'cute-elephant',
    title: 'Cute Elephant',
    emoji: '🐘',
    difficulty: 'medium',
    description: 'A friendly elephant with a long curvy trunk.',
    steps: toSteps([
      { title: 'Big body', instruction: 'Draw a large rounded body in the middle.' },
      { title: 'Add the head', instruction: 'Add a big round head on one side.' },
      { title: 'Long trunk', instruction: 'Draw a long, curvy trunk coming down from the head.' },
      { title: 'Ears & legs', instruction: 'Add two big floppy ears and four thick legs.' },
      { title: 'Friendly face', instruction: 'Draw two kind eyes and a little smile.' },
      { title: 'Color it in', instruction: 'Color your elephant gray — or any color you like!' },
    ]),
  },
  {
    slug: 'cat-face',
    title: 'Cat Face',
    emoji: '🐱',
    difficulty: 'easy',
    description: 'A round, happy cat face.',
    steps: toSteps([
      { title: 'Round face', instruction: 'Draw a big circle for the cat face.' },
      { title: 'Pointy ears', instruction: 'Add two triangle ears on top.' },
      { title: 'Cat features', instruction: 'Draw two eyes, a little nose, and whiskers.' },
      { title: 'Color it in', instruction: 'Color your cat and give it a happy smile!' },
    ]),
  },
  {
    slug: 'dog',
    title: 'Dog',
    emoji: '🐶',
    difficulty: 'easy',
    description: 'A playful puppy with floppy ears.',
    steps: toSteps([
      { title: 'Head & body', instruction: 'Draw a circle for the head and an oval for the body.' },
      { title: 'Ears & legs', instruction: 'Add two floppy ears and four little legs.' },
      { title: 'Face & tail', instruction: 'Draw eyes, a nose, and a wagging tail.' },
      { title: 'Color it in', instruction: 'Color your puppy. Woof!' },
    ]),
  },
  {
    slug: 'butterfly',
    title: 'Butterfly',
    emoji: '🦋',
    difficulty: 'medium',
    description: 'A pretty butterfly with patterned wings.',
    steps: toSteps([
      { title: 'Body', instruction: 'Draw a thin oval in the middle for the body.' },
      { title: 'Top wings', instruction: 'Add two big wings at the top.' },
      { title: 'Bottom wings', instruction: 'Add two smaller wings at the bottom.' },
      { title: 'Antennae', instruction: 'Draw two little antennae on the head.' },
      { title: 'Wing patterns', instruction: 'Add dots and shapes on the wings.' },
      { title: 'Color it in', instruction: 'Color your butterfly with bright, happy colors!' },
    ]),
  },
  {
    slug: 'fish',
    title: 'Fish',
    emoji: '🐟',
    difficulty: 'easy',
    description: 'A little fish blowing bubbles.',
    steps: toSteps([
      { title: 'Body', instruction: 'Draw an oval for the fish body.' },
      { title: 'Tail', instruction: 'Add a triangle tail at the back.' },
      { title: 'Eye & fins', instruction: 'Draw a big eye and a couple of fins.' },
      { title: 'Color it in', instruction: 'Color your fish and add some bubbles!' },
    ]),
  },
  {
    slug: 'dinosaur',
    title: 'Dinosaur',
    emoji: '🦖',
    difficulty: 'hard',
    description: 'A friendly dino with spiky back plates.',
    steps: toSteps([
      { title: 'Body', instruction: 'Draw a big rounded body.' },
      { title: 'Neck & head', instruction: 'Add a long neck and a small head.' },
      { title: 'Tail', instruction: 'Draw a long, pointy tail.' },
      { title: 'Legs', instruction: 'Add four strong legs underneath.' },
      { title: 'Spikes', instruction: 'Draw triangle spikes along the back.' },
      { title: 'Face', instruction: 'Add an eye and a friendly mouth.' },
      { title: 'Tidy up', instruction: 'Erase extra lines and make it neat.' },
      { title: 'Color it in', instruction: 'Color your dino green — or any color you like!' },
    ]),
  },
  // Placeholders (12)
  { slug: 'lion', title: 'Lion', emoji: '🦁', difficulty: 'medium' },
  { slug: 'rabbit', title: 'Rabbit', emoji: '🐰', difficulty: 'easy' },
  { slug: 'bear', title: 'Bear', emoji: '🐻', difficulty: 'easy' },
  { slug: 'owl', title: 'Owl', emoji: '🦉', difficulty: 'medium' },
  { slug: 'frog', title: 'Frog', emoji: '🐸', difficulty: 'easy' },
  { slug: 'turtle', title: 'Turtle', emoji: '🐢', difficulty: 'medium' },
  { slug: 'penguin', title: 'Penguin', emoji: '🐧', difficulty: 'easy' },
  { slug: 'fox', title: 'Fox', emoji: '🦊', difficulty: 'medium' },
  { slug: 'monkey', title: 'Monkey', emoji: '🐵', difficulty: 'medium' },
  { slug: 'giraffe', title: 'Giraffe', emoji: '🦒', difficulty: 'hard' },
  { slug: 'snail', title: 'Snail', emoji: '🐌', difficulty: 'easy' },
  { slug: 'ladybug', title: 'Ladybug', emoji: '🐞', difficulty: 'easy' },
]);
