import type { Category } from '@/types';

/** The 8 V1 content categories (docs/01 §D, docs/04 §7). */
export const CATEGORIES: Category[] = [
  {
    id: 'alphabets',
    slug: 'alphabets',
    name: 'Alphabets',
    description: 'Letters A–Z with fun friends.',
    emoji: '🔤',
    accentKey: 'violet',
    sortOrder: 1,
  },
  {
    id: 'numbers',
    slug: 'numbers',
    name: 'Numbers',
    description: 'Count and draw 0 through 9.',
    emoji: '🔢',
    accentKey: 'sky',
    sortOrder: 2,
  },
  {
    id: 'animals',
    slug: 'animals',
    name: 'Animals',
    description: 'Cute creatures big and small.',
    emoji: '🐘',
    accentKey: 'mint',
    sortOrder: 3,
  },
  {
    id: 'vehicles',
    slug: 'vehicles',
    name: 'Vehicles',
    description: 'Cars, buses, planes, and more.',
    emoji: '🚗',
    accentKey: 'coral',
    sortOrder: 4,
  },
  {
    id: 'space',
    slug: 'space',
    name: 'Space',
    description: 'Rockets, planets, and robots.',
    emoji: '🚀',
    accentKey: 'violetDeep',
    sortOrder: 5,
  },
  {
    id: 'nature',
    slug: 'nature',
    name: 'Nature',
    description: 'Trees, flowers, and weather.',
    emoji: '🌳',
    accentKey: 'mint',
    sortOrder: 6,
  },
  {
    id: 'curriculum',
    slug: 'curriculum',
    name: 'School',
    description: 'Everyday things from school.',
    emoji: '🏫',
    accentKey: 'sun',
    sortOrder: 7,
  },
  {
    id: 'cards',
    slug: 'cards',
    name: 'Cards',
    description: 'Make a card for someone special.',
    emoji: '💌',
    accentKey: 'coral',
    sortOrder: 8,
  },
];
